### ISSUE TITLE
Use vagrant-cachier

### ISSUE THREAD

**Issue by opticyclic** [Enalean/tuleap-vagrant#2]
Your box requires lots of files to be installed with yum so it would be useful to use vagrant-cachier to cache the packages and save bandwidth in cases of provisioning multiple times.
http://fgrehm.viewdocs.io/vagrant-cachier/usage/

**Comment by vaceletm** [comment]
Thanks for reporting that but we no longer maintain this repository.
Please have a look at our docker package instead: https://registry.hub.docker.com/u/enalean/tuleap-aio/
