### ISSUE TITLE
Readme Refers To Incorrect Clone

### ISSUE THREAD

**Issue by opticyclic** [Enalean/tuleap-vagrant#3]
The readme doesn't match what the dev docs say
http://tuleap-documentation.readthedocs.org/en/latest/developer-guide/dev-setup.html

However, the gitolite user requires a password.

Cloning the github repo appears to work and the readme should reflect this.

**Comment by vaceletm** [comment]
For development purpose, the recommended way of doing it is to use the docker image: https://registry.hub.docker.com/u/enalean/tuleap-aio-dev/
