### ISSUE TITLE
Virtualbox Guest Additions Don't Install

### ISSUE THREAD

**Issue by opticyclic** [Enalean/tuleap-vagrant#4]
Using Virtualbox 4.3.28 the Guest Additions don't install.

    [vagrant@vagrant-centos65 init]$ sudo ./vboxadd setup
    Removing existing VirtualBox non-DKMS kernel modules       [  OK  ]
    Building the VirtualBox Guest Additions kernel modules
    The headers for the current running kernel were not found. If the following
    module compilation fails then this could be the reason.
    The missing package can be probably installed with
    yum install kernel-devel-2.6.32-431.1.2.0.1.el6.x86_64
    
    Building the main Guest Additions module                   [FAILED]
    (Look at /var/log/vboxadd-install.log to find out what went wrong)
    Doing non-kernel setup of the Guest Additions              [  OK  ]
    [vagrant@vagrant-centos65 init]$ sudo yum install kernel-devel-$(uname -r)
    Loaded plugins: fastestmirror
    Setting up Install Process
    Loading mirror speeds from cached hostfile
     * base: mirror.netflash.net
     * epel: www.muug.mb.ca
     * extras: centos.mirror.gtcomm.net
     * updates: centos.mirror.gtcomm.net
    No package kernel-devel-2.6.32-431.1.2.0.1.el6.x86_64 available.
    Error: Nothing to do
    [vagrant@vagrant-centos65 init]$

`sudo rpm -ivh http://bay.uchicago.edu/centos-vault/6.5/updates/x86_64/Packages/kernel-devel-2.6.32-431.1.2.0.1.el6.x86_64.rpm` is one workaround for this issue.

**Comment by vaceletm** [comment]
Project no longer maintained
