### ISSUE TITLE
User codendiadm Does Not Exist

### ISSUE THREAD

**Issue by opticyclic** [Enalean/tuleap-vagrant#5]
`vagrant up` fails with 

    GuestAdditions 4.3.28 running --- OK.
    ==> default: Checking for guest additions in VM...
    ==> default: Configuring and enabling network interfaces...
    ==> default: Mounting shared folders...
        default: /vagrant => C:/Users/morgana/Projects/GitHub/tuleap-vagrant
        default: /mnt/tuleap_sources => C:/Users/morgana/Projects/GitHub/tuleap
    Failed to mount folders in Linux guest. This is usually because
    the "vboxsf" file system is not available. Please verify that
    the guest additions are properly installed in the guest and
    can work properly. The command attempted was:
    
    mount -t vboxsf -o uid=`id -u codendiadm`,gid=`getent group codendiadm | cut -d: -f3` mnt_tuleap_sources /mnt/tuleap_sourcesmount -t vboxsf -o uid=`id -u codendiadm`,gid=`id -g codendiadm` mnt_tuleap_sources /mnt/tuleap_sources
    
    The error output from the last command was:
    
    id: codendiadm: No such user
    id: codendiadm: No such user
    uid= requires an argument (i.e. uid==<arg>)

The `codendiadm` user does not exist.

    [vagrant@vagrant-centos65 ~]$ cut -d: -f1 /etc/passwd|grep codendiadm|wc -l
    0

**Comment by vaceletm** [comment]
Project no longer maintained
