### ISSUE TITLE
Missing Role tuleap_development In Run List

### ISSUE THREAD

**Issue by opticyclic** [Enalean/tuleap-vagrant#6]
Chef fails to provision properly with the following error

    ==> default: /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.2/bin/chef-solo:25:in `<top (required)>'
    ==> default: /usr/bin/chef-solo:23:in `load'
    ==> default: /usr/bin/chef-solo:23:in `<main>'
    ==> default: [2015-07-25T00:29:23+00:00] ERROR: The expanded run list includes nonexistent roles: tuleap_development
    ==> default:
    ==> default: ================================================================================
    ==> default: Error expanding the run_list:
    ==> default: ================================================================================
    ==> default:
    ==> default:
    ==> default: Missing Role(s) in Run List:
    ==> default: ----------------------------
    ==> default: * tuleap_development included by 'top level'
    ==> default:
    ==> default:
    ==> default: Original Run List
    ==> default: -----------------
    ==> default: * role[tuleap_development]
    ==> default:
    ==> default:
    ==> default: [2015-07-25T00:29:22+00:00] INFO: Forking chef instance to converge...
    ==> default: [2015-07-25T00:29:22+00:00] DEBUG: Fork successful. Waiting for new chef pid: 3098
    ==> default: [2015-07-25T00:29:23+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    Chef never successfully completed! Any errors should be visible in the
    output above. Please fix your recipes so that they properly complete.

**Comment by vaceletm** [comment]
We no longer use chef, hence we will no longer fix the coobooks
